# SPDX-License-Identifier: BSD-2-Clause
name: CI

on:
  pull_request:
    branches: [ main ]

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Force-Build:
    timeout-minutes: 90

    strategy:
        fail-fast: false
        matrix:
            os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Build Force
      run: |
        git clone --depth 1 --single-branch --branch develop https://github.com/davidfrantz/force
        cd force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: force-${{ matrix.os }}
        path: force/force-${{ matrix.os }}.tar.bz2
        retention-days: 5
